server:
  port: 8761
spring:
  application:
    name: choss-registry
  profiles:
    active: dev


logging:
  config: classpath:logback-spring.xml
  path: target/logs
  file: registry-center.log
  level:
    root: info