spring:
  redis:
    host: 192.168.88.1241
    port: 6379
    password: 
    timeout: 0         # 连接超时时间（毫秒）
    database: 0
    pool:
      max-total: 28        # 连接池最大连接数（使用负值表示没有限制）
      max-wait-millis: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 18         # 连接池中的最大空闲连接
      min-idle: 1          # 连接池中的最小空闲连接
    cluster:
      nodes:
      - 192.168.88.241:7000
      - 192.168.88.241:7001
      - 192.168.88.241:7002
      - 192.168.88.241:7003
      - 192.168.88.241:7004
      - 192.168.88.241:7005